name: Link Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: >-
            --verbose
            --no-progress
            --accept 200,206,429
            "**/*.md"
            "**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}